modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
issueTrackerURL="https://github.com/ochotonida/artifacts/issues"

[[mods]]
modId="artifacts"
version="${version}"
displayName="Artifacts"
displayURL="https://www.curseforge.com/minecraft/mc-mods/artifacts"
logoFile= "logo.png"
authors="ochotonida"
description='''Adds various new powerful uncraftable items to make exploration a bit more interesting'''

[[mixins]]
config="mixins.artifacts.common.json"
[[mixins]]
config="mixins.artifacts.neoforge.json"

[[dependencies.artifacts]]
    modId="neoforge"
    type="required"
    ordering="NONE"
    side="BOTH"

[[dependencies.artifacts]]
    modId = "minecraft"
    type="required"
    versionRange = "[1.20.5,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.artifacts]]
    modId = "curios"
    type="required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.artifacts]]
    modId = "cloth_config"
    type="required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.artifacts]]
    modId = "architectury"
    type="required"
    ordering="NONE"
    side="BOTH"